dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "remembrall"
include(":app")
include(":home")
include(":auth")
include(":user")
include(":date")
include(":task")
include(":login")
include(":oauth")
include(":common")
include(":splash")
include(":config")
include(":profile")
include(":rxutils")
include(":ui:color")
include(":task:add")
include(":dateimpl")
include(":authimpl")
include(":calendar")
include(":ui")
include(":task:list")
include(":oauthimpl")
include(":mobiusutils")
include(":authandroid")
include(":gmstaskutils")
include(":calendarimpl")
include(":taskimpl")
include(":common-schedule")
include(":coroutinesutils")
include(":activityprovider")
include(":activityproviderimpl")
include(":task:taskpriorityextensions")
include(":ui:icons")
